=== Nemferno/Tower-Defense-Game/Tower Defense Game/asset/LevelData/LevelDataStructure.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY virus "virus">
<!ENTITY darkrover "darkrover">
<!ENTITY worm "worm">
<!ENTITY immortal "immortal">
<!ENTITY trojan "trojan">

<!ELEMENT LevelData (Level)>
<!ELEMENT Level (Round+)>
<!ELEMENT Round (Enemies)>
<!ELEMENT Enemies (#PCDATA)>

<!ATTLIST Level name CDATA #REQUIRED>
<!ATTLIST Level id CDATA #REQUIRED>
<!ATTLIST Level subid CDATA #REQUIRED>
<!ATTLIST Level mapLoc CDATA #REQUIRED>
<!ATTLIST Level mapTileLoc CDATA #REQUIRED>
<!ATTLIST Level startCurrency CDATA #REQUIRED>
<!ATTLIST Level type CDATA #REQUIRED>
<!ATTLIST Level bossRound CDATA #REQUIRED>
<!ATTLIST Level bossType CDATA #REQUIRED>
<!ATTLIST Round restTime CDATA #REQUIRED>
<!ATTLIST Round respawnTime CDATA #IMPLIED>
<!ATTLIST Round loop CDATA #IMPLIED>
<!ATTLIST Round unitAmount CDATA #REQUIRED>
<!ATTLIST Round cReward CDATA #REQUIRED>

=== Nemferno/Tower-Defense-Game/Tower Defense Game/asset/LevelData/AlphaMapData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LevelData SYSTEM "asset/LevelData/LevelDataStructure.dtd">
<LevelData>
    <Level name="Alpha Map" id="1" subid="1" mapLoc="asset/LevelMaps/AlphaMap.tmx"
        mapTileLoc="asset/LevelMaps" startCurrency="800" type="survival"
        bossRound="10" bossType="aberration" cBReward="500">
        
        <Round unitAmount="10" restTime="5000" respawnTime="2000" cReward="125">
            <Enemies>&virus;</Enemies>
        </Round>
        
        <Round unitAmount="15" restTime="5000" respawnTime="2000" cReward="150">
            <Enemies>&virus;</Enemies>
        </Round>

        <Round unitAmount="15" restTime="5000" respawnTime="2000" cReward="150">
            <Enemies>&virus;</Enemies>
        </Round>
        
        <Round unitAmount="13" restTime="5000" respawnTime="2000" cReward="135">
            <Enemies>&virus;</Enemies>
        </Round>
        
        <Round unitAmount="18" restTime="5000" respawnTime="2000" cReward="175">
            <Enemies>&virus;</Enemies>
        </Round>        
        
        <Round unitAmount="10" restTime="5000" respawnTime="2000" cReward="215">
            <Enemies>&virus;,&immortal;</Enemies>
        </Round>        

        <Round unitAmount="15" restTime="5000" respawnTime="2000" cReward="230">
            <Enemies>&virus;,&immortal;</Enemies>
        </Round>

		<Round unitAmount="13" restTime="5000" respawnTime="2000" cReward="225">
            <Enemies>&virus;,&immortal;</Enemies>
        </Round>        
        
		<Round unitAmount="18" restTime="5000" respawnTime="2000" cReward="275">
            <Enemies>&virus;,&immortal;</Enemies>
        </Round>
		
		<!-- Rounds 1 - 9 -->
		
		<Round unitAmount="20" restTime="5000" respawnTime="1750" cReward="275">
		    <Enemies>&virus;,&immortal;</Enemies>
		</Round>
		
		<Round unitAmount="22" restTime="5000" respawnTime="1750" cReward="290">
		    <Enemies>&virus;,&immortal;</Enemies>
		</Round>
		
		<Round unitAmount="25" restTime="5000" respawnTime="1850" cReward="300">
		    <Enemies>&virus;,&immortal;,&worm;</Enemies>
		</Round>
		
		<Round unitAmount="18" restTime="5000" respawnTime="1750" cReward="305">
		    <Enemies>&virus;,&immortal;,&worm;</Enemies>
		</Round>
		
		<!-- Rounds 11 - 14 -->
		
		<Round unitAmount="23" restTime="5000" respawnTime="1690" cReward="320">
		    <Enemies>&virus;,&immortal;</Enemies>
		</Round>

		<Round unitAmount="23" restTime="5000" respawnTime="1680" cReward="322">
		    <Enemies>&virus;,&immortal;</Enemies>
		</Round>
		
		<Round unitAmount="26" restTime="5000" respawnTime="1650" cReward="345">
		    <Enemies>&virus;,&immortal;,&darkrover;</Enemies>
		</Round>
		
		<Round unitAmount="15" restTime="5000" respawnTime="1500" cReward="375">
		    <Enemies>&virus;,&immortal;</Enemies>
		</Round>
		
		<!-- Rounds 16 - 19 -->
		
		<Round unitAmount="20" restTime="5000" respawnTime="1890" cReward="375">
		    <Enemies>&virus;,&immortal;</Enemies>
		</Round>

		<Round unitAmount="23" restTime="5000" respawnTime="1890" cReward="375">
		    <Enemies>&virus;,&immortal;</Enemies>
		</Round>		
		
		<Round unitAmount="25" restTime="5000" respawnTime="1890" cReward="380">
		    <Enemies>&virus;,&immortal;</Enemies>
		</Round>
		
		<Round unitAmount="15" restTime="5000" respawnTime="1890" cReward="395">
		    <Enemies>&virus;,&immortal;,&worm;</Enemies>
		</Round>
		
		<!-- Rounds 21 - 24 -->
		
		<Round unitAmount="20" restTime="5000" respawnTime="2000" cReward="410">
		    <Enemies>&virus;,&immortal;,&darkrover;</Enemies>
		</Round>
		
		<Round unitAmount="24" restTime="7500" respawnTime="2000" cReward="420">
		    <Enemies>&virus;,&immortal;,&darkrover;</Enemies>
		</Round>
		
		<Round unitAmount="27" restTime="7500" respawnTime="1900" cReward="445">
		    <Enemies>&virus;,&immortal;,&darkrover;,&trojan;</Enemies>
		</Round>
		
		<Round unitAmount="35" restTime="10000" respawnTime="1800" cReward="475">
		    <Enemies>&virus;,&immortal;,&darkrover;,&trojan;</Enemies>
		</Round>
		
		<!-- Rounds 26 - 29 -->
		
		<Round unitAmount="40" restTime="10000" respawnTime="1800" cReward="500" loop="true">
		    <Enemies>&virus;,&immortal;,&darkrover;,&trojan;</Enemies>
		</Round>
		
    </Level>
</LevelData>

=== Nemferno/Tower-Defense-Game/Tower Defense Game/asset/LevelData/LevelDataTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- PUBLIC "" "http://s464830726.onlinehome.us/xodia/arcade/tdg/asset/LevelData/LevelDataStructure.dtd" -->
<!DOCTYPE LevelData SYSTEM "asset/LevelData/LevelDataStructure.dtd">
<LevelData>
    <!-- When choosing the type of level, it is important to note
    	 that there are two types... survival & regular 
    	 RestTime is in millisecond (1000 ms = 1s) -->
    <Level name="Test Map" id="-1" subid="1" mapLoc="asset/EndlessModeMap3.tmx" 
        mapTileLoc="asset" startCurrency="200" type="regular">
        <!-- Only put loop if it is required -->
        <Round unitAmount="1" restTime="1000">
            <!-- Note: The Naming MUST Be Correct So That The Game Can
            		   Take That Information Easy Since The Software Compares
            		   The String On The XML With The Name Of The Enum -->
            <Enemies>&virus;</Enemies>
        </Round>
        <Round unitAmount="1" restTime="1000">
            <Enemies>&virus;</Enemies>
        </Round>
        <Round unitAmount="1" restTime="1000">
            <Enemies>&immortal;,&worm;</Enemies>
        </Round>
    </Level>
</LevelData>

=== Nemferno/Tower-Defense-Game/Tower Defense Game/asset/LevelData/EndlessData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LevelData SYSTEM "asset/LevelData/LevelDataStructure.dtd">
<LevelData>
    <!-- When choosing the type of level, it is important to note
    	 that there are two types... survival & regular 
    	 RestTime is in millisecond (1000 ms = 1s) -->
    <Level name="Test Map" id="-1" subid="1" mapLoc="asset/EndlessModeMap3.tmx" 
        mapTileLoc="asset" startCurrency="550" type="survival" bossRound="5" bossType="aberration" cBReward="250">
        <!-- Only put loop if it is required -->
        <Round unitAmount="20" restTime="5000" respawnTime="250" cReward="50">
            <!-- Note: The Naming MUST Be Correct So That The Game Can
            		   Take That Information Easy Since The Software Compares
            		   The String On The XML With The Name Of The Enum -->
            <Enemies>&virus;</Enemies>
        </Round>
        <Round unitAmount="15" restTime="5000" respawnTime="2500" cReward="50">
            <Enemies>&virus;</Enemies>
        </Round>
        <Round unitAmount="20" restTime="5000" respawnTime="2500" cReward="50">
            <Enemies>&virus;</Enemies>
        </Round>
        <Round unitAmount="25" restTime="5000" respawnTime="2500" cReward="50">
            <Enemies>&virus;</Enemies>
        </Round>
        <Round unitAmount="25" restTime="5000" respawnTime="2500" cReward="50">
            <Enemies>&virus;</Enemies>
        </Round>
        <Round unitAmount="25" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&immortal;,&virus;</Enemies>
        </Round>
        <Round unitAmount="25" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&immortal;,&virus;</Enemies>
        </Round>
        <Round unitAmount="35" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&immortal;,&virus;</Enemies>
        </Round>
        <Round unitAmount="15" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&immortal;,&virus;,&darkrover;</Enemies>
        </Round>
        <Round unitAmount="15" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&immortal;,&virus;,&darkrover;</Enemies>
        </Round>
        <Round unitAmount="15" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&immortal;,&virus;,&darkrover;</Enemies>
        </Round>
        <Round unitAmount="20" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&immortal;,&virus;,&darkrover;</Enemies>
        </Round>
        <Round unitAmount="15" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&virus;,&worm;</Enemies>
        </Round>
        <Round unitAmount="10" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&virus;,&worm;</Enemies>
        </Round>
        <Round unitAmount="5" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&virus;,&worm;</Enemies>
        </Round>
        <Round unitAmount="15" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&virus;,&worm;,&darkrover;,&immortal;,&trojan;</Enemies>
        </Round>
        <Round unitAmount="25" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&virus;,&worm;,&darkrover;,&immortal;,&trojan;</Enemies>
        </Round>
        <Round unitAmount="35" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&virus;,&worm;,&darkrover;,&immortal;,&trojan;</Enemies>
        </Round>
        <Round unitAmount="40" restTime="5000" respawnTime="2500" cReward="105">
            <Enemies>&virus;,&worm;,&darkrover;,&immortal;,&trojan;</Enemies>
        </Round>
        <Round unitAmount="50" restTime="5000" respawnTime="2500" cReward="105" loop="true">
            <Enemies>&virus;,&worm;,&darkrover;,&immortal;,&trojan;</Enemies>
        </Round>
    </Level>
</LevelData>
